version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
      # context: .
      # dockerfile: Dockerfile
    ports:
      - '5000:5000'
    # volumes:
    #   - ./server:/usr/src/app/server
    links:
      - mongo
    depends_on:
      - mongo
  # client:
  #   container_name: todo-client
  #   restart: always
  #   build: ./client
  #   # dockerfile: Dockerfile-alternate
  #   volumes:
  #     - ./client:/usr/src/app/client
  #   ports:
  #     - '3020:3020'
  mongo:
    image: mongo:latest
    # container-name: "mymongo"
    # restart: always
    ports:
      - '27017:27017'
